---
- name: Create Docker Network
  hosts: all
  become: yes
  tasks:
      - name: Create {{ docker_network }}
        docker_network:
            name: '{{ docker_network }}'
            state: present

      - name: Create portainer_data volume
        docker_volume:
            name: portainer_data
            state: present
