---
- name: Create Docker Network
  hosts: all
  become: yes
  tasks:
      - name: Create {{ docker_network }}
        docker_network:
            name: '{{ docker_network }}'
            state: present
