---
- name: Deploy Web Client
  hosts: all
  become: yes

  vars:
      dockerhub_image: 'jonasaugust12/brix-web'
      image_tag: 'latest'
      container_name: 'brix-web'
      host_port: 3000
      container_port: 3000

  tasks:
      - name: Pull web client image from Docker Hub
        docker_image:
            name: '{{ dockerhub_image }}:{{ image_tag }}'
            source: pull
            # Efficiently pull only when necessary

      - name: Deploy web client container
        docker_container:
            name: '{{ container_name }}'
            image: '{{ dockerhub_image }}:{{ image_tag }}'
            state: started
            restart_policy: always
            published_ports:
                - '{{ host_port }}:{{ container_port }}'
            labels:
                com.centurylinklabs.watchtower.enable: 'true'

      - name: Wait for web client to be healthy
        uri:
            url: 'http://localhost:{{ host_port }}'
            status_code: [200, 301, 302]
        register: result
        until: result.status in [200, 301, 302]
        retries: 10
        delay: 5

      - name: Cleanup unused Docker resources
        shell: |
            docker container prune -f
            docker image prune -af
        args:
            executable: /bin/bash
        register: cleanup_result

      - name: Show deployment status
        debug:
            msg: 'Web Client is successfully deployed and reachable at http://{{ inventory_hostname }}:{{ host_port }}'
