---
# Master playbook to orchestrate the entire deployment flow

# Deploy Prod-Dev flow
- import_playbook: install_docker.yml
- import_playbook: create_network.yml
- import_playbook: deploy_infra.yml
- import_playbook: deploy_app.yml
# Deploy single host flow
#- import_playbook: install_docker.yml
#- import_playbook: deploy_compose.yml
# Deploy single host flow step by step
#- import_playbook: install_docker.yml
#- import_playbook: create_network.yml
#- import_playbook: deploy_web_client.yml
#- import_playbook: deploy_nginx.yml
#- import_playbook: deploy_portainer.yml
