[webserver]
# Replace with your actual EC2 instance IP
# Default user for Ubuntu EC2 is 'ubuntu'
# Ensure your SSH private key path is correct
11.1111.11.111 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/my-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
