name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup pnpm
              uses: pnpm/action-setup@v5

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '22'

            - name: Install dependencies
              run: pnpm install

            - name: Run build
              run: pnpm run build
              env:
                  NEXT_PUBLIC_BACKEND_URL: http://localhost:8080
