name: deploy-app

on:
    workflow_run:
        workflows: ['push-image']
        branches: [main]
        types:
            - completed

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'

            - name: Install Ansible
              run: |
                  python -m pip install --upgrade pip
                  pip install ansible

            - name: Set up SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  # Replace with your actual server IP or use a secret
                  ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

            - name: Create temporary inventory
              run: |
                  echo "[webserver]" > inventory_ci.ini
                  echo "${{ secrets.REMOTE_HOST }} ansible_user=${{ secrets.REMOTE_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3" >> inventory_ci.ini

            - name: Deploy via Ansible
              run: |
                  # The tag should match the one generated in docker-push.yml
                  # which is: latest-$(git rev-parse --short HEAD)
                  SHORT_SHA=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7)
                  ansible-playbook ansible/deploy_app.yml \
                    -i inventory_ci.ini \
                    -e "image_tag=latest-$SHORT_SHA"
